### ISSUE TITLE
 push 后自动部署到 hugging face

### ISSUE THREAD

**Issue by zzzzls** [vvanglro/Emoji-Chat#3]
https://zzzzls-emoji-chat.hf.space

**Comment by vvanglro** [comment]
redis也可以部署嘛 没试过 PR个部署教程

**Comment by zzzzls** [comment]
> redis也可以部署嘛 没试过 PR个部署教程

redis 可以使用 [Redislabs](https://app.redislabs.com/#/login)， 免费 30M 空间

**Comment by shyragdoll** [comment]
再加个hook 自动推huggingface仓库就完美了😁

**Comment by vvanglro** [comment]
已经解决了redis依赖问题，可以直接Duplicate这个空间就行  https://huggingface.co/spaces/vvanglro/emoji-chat

**Comment by shyragdoll** [comment]
> 已经解决了redis依赖问题，可以直接Duplicate这个空间就行 https://huggingface.co/spaces/vvanglro/emoji-chat

直接把这个加到Readme里 https://huggingface.co/spaces/vvanglro/emoji-chat?duplicate=true
