### ISSUE TITLE
用 js 实现 obscure64 如何？

### ISSUE THREAD

**Issue by zzzzls** [vvanglro/Emoji-Chat#7]
加解密放在客户端，一切就变得简单了

**Comment by vvanglro** [comment]
上百个emoji都放在js里嘛 https://github.com/vvanglro/Emoji-Chat/blob/main/emoji_chat/emoji.json

哪些地方变简单了

我感觉还是在服务端比较好管理操作些吧

**Comment by zzzzls** [comment]
> 上百个emoji都放在js里嘛 https://github.com/vvanglro/Emoji-Chat/blob/main/emoji_chat/emoji.json
> 
> 哪些地方变简单了
> 
> 我感觉还是在服务端比较好管理操作些吧

- 最新的两个 todo 就变简单了
- emoji 不是一个参数嘛 初始化房间的时候和客户端同步一下

**Comment by vvanglro** [comment]
> * 最新的两个 todo 就变简单了

现在已经把emoji_msg和msg一起发到客户端上了，只是展示的emoji_msg

至于将自己的消息也展示为emoji_msg，send出去后接收ws的消息，如果消息中的uid等于缓存中的uid就展示到右边，这样就实现自己发出去的消息也是emoji_msg了。(想了下为啥要区分左右边，看了下电报的群组不管自己还是别人都在左边展示的)

> * emoji 不是一个参数嘛 初始化房间的时候和客户端同步一下
初始化房间的时候，服务器把65个emoji下放给客户端嘛？我下午刚改的是每次消息都用不同emoji去加密的 哈哈哈
